# Generated by doctest: do not edit by hand
# Please edit file in R/function.R

test_that("Doctest: check_temperature_inspector", {
  # Created from @doctest for `check_temperature_inspector`
  # Source file: R/function.R
  # Source line: 2665
  dataframe1 <- data.frame(activity_id = c("1", "2", "3"), activity_seasurfacetemperature = c(20, 4, 35))
  expect_equal(check_temperature_inspector(dataframe1, output = "report"), structure(list(activity_id = c("1", "2", "3"), logical = c(TRUE,
    FALSE, FALSE), activity_seasurfacetemperature = c(20, 4, 35)), row.names = c(NA, 3L), class = "data.frame"))
})

