# Generated by doctest: do not edit by hand
# Please edit file in R/function_specific_check.R

test_that("Doctest: plot_temporal_limit_windows", {
  # Created from @doctest for `plot_temporal_limit_windows`
  # Source file: R/function_specific_check.R
  # Source line: 290
  expect_equal(plot_temporal_limit_windows("0", as.Date("2020/01/02")),
  "<b>Trip information : </b><br>\n          <ul><li>Vessel code : 0</li>\n          <li>Trip end date : 2020-01-02</li></ul>")
})

