# Generated by doctest: do not edit by hand
# Please edit file in R/function_specific_check.R

test_that("Doctest: plot_position_data", {
  # Created from @doctest for `plot_position_data`
  # Source file: R/function_specific_check.R
  # Source line: 353
  dataframe1 <- data.frame(activity_id = c("1", "2"), activity_position = c("POINT (0 0)", "POINT (0 0)"), type = c("Sea", "Sea"), ocean_label = c(
    "ocean_1", "ocean_2"), ocean_calculate = c("ocean_1", "ocean_1"), activity_crs = c(4326, 4326))
  dataframe2 <- data.frame(activity_id = c("1", "2"), vessel_code = c("0", "0"), trip_enddate = as.Date(c("2020/01/10", "2020/01/10")),
  activity_date = as.Date(c("2020/01/09", "2020/01/10")), activity_number = c(1L, 1L))
  expect_equal(plot_position_data(dataframe1, dataframe2), list(`1` = list(data = structure(list(activity_position = "POINT (0 0)", activity_crs = 4326),
  class = "data.frame", row.names = 1L), vessel_code = "0", trip_enddate = structure(18271, class = "Date"), activity_date = structure(18270, class = "Date"),
  activity_number = 1L, type = "Sea", ocean_label = "ocean_1", ocean_calculate = "ocean_1", X = "E0°0'", Y = "N0°0'"), `2` = list(data = structure(
    list(activity_position = "POINT (0 0)", activity_crs = 4326), class = "data.frame", row.names = 2L), vessel_code = "0", trip_enddate = structure(
    18271, class = "Date"), activity_date = structure(18271, class = "Date"), activity_number = 1L, type = "Sea", ocean_label = "ocean_2",
  ocean_calculate = "ocean_1", X = "E0°0'", Y = "N0°0'")))
})

