# Generated by doctest: do not edit by hand
# Please edit file in R/function_specific_check.R

test_that("Doctest: plot_anapo_data", {
  # Created from @doctest for `plot_anapo_data`
  # Source file: R/function_specific_check.R
  # Source line: 1203
  dataframe1 <- data.frame(activity_id = c("4", "4", "4", "6", "6", "6", "2", "2", "2"), activity_date = as.Date(c("2020/01/13", "2020/01/13", "2020/01/13", "2020/01/13",
    "2020/01/13", "2020/01/13", "2020/01/12", "2020/01/12", "2020/01/12")), activity_time = c("03:12:34", "03:12:34", "03:12:34", "23:26:47", "23:26:47", "23:26:47",
    "05:26:01", "05:26:01", "05:26:01"), activity_position = c("POINT (2.6 3.8)", "POINT (2.6 3.8)", "POINT (2.6 3.8)", "POINT (3 0.6)", "POINT (3 0.6)", "POINT (3 0.6)",
    "POINT (0 0)", "POINT (0 0)", "POINT (0 0)"), activity_crs = c(4326, 4326, 4326, 4326, 4326, 4326, 4326, 4326, 4326), vms_date = as.Date(c("2020/01/13", "2020/01/13",
    "2020/01/12", "2020/01/13", "2020/01/13", "2020/01/12", "2020/01/12", "2020/01/13", "2020/01/13")), vms_time = c("10:55:15", "22:32:17", "15:26:01", "10:55:15",
    "22:32:17", "15:26:01", "15:26:01", "10:55:15", "22:32:17"), vms_position = c("POINT (0 0.1)", "POINT (3 0.3)", "POINT (4 4)", "POINT (0 0.1)", "POINT (3 0.3)",
    "POINT (4 4)", "POINT (4 4)", "POINT (0 0.1)", "POINT (3 0.3)"), distance = c(271.445826973379, 211.507663354955, 84.71741855987, 182.602328607533, 18.012165417519,
    212.768118823317, 339.502583, 6.004055, 181.019203), duration = c(-27761000, -69583000, -44007000, 45092000, 3270000, 28846000, NA, NA, NA), score = c(0, 0, 0, 0,
    0.209441144555651, 0, NA, NA, NA), vms_crs = c(4326, 4326, 4326, 4326, 4326, 4326, 4326, 4326, 4326))
  units::install_unit("NM", "1852 m", "Nautical mile")
  dataframe1$distance <- units::set_units(dataframe1$distance, NM)
  units::install_unit("ms", "1000 secs", "Milliseconds")
  dataframe1$duration <- units::set_units(dataframe1$duration, ms)
  dataframe2 <- data.frame(trip_id = c("1", "1", "1"), vessel_code = c("0", "0", "0"), trip_enddate = as.Date(c("2020/01/20", "2020/01/20", "2020/01/20")), activity_id = c(
    "2", "4", "6"), activity_date = as.Date(c("2020/01/12", "2020/01/13", "2020/01/13")), activity_number = c(1L, 1L, 1L), vesselactivity_code = c("2", "6", "13"))
  dataframe3 <- data.frame(transmittingbuoy_id = c("1"), transmittingbuoyoperation_code = c("4"), activity_id = c("6"))
  expect_equal(plot_anapo_data(dataframe1, dataframe2, dataframe3), list(`2` = list(data_trip = structure(list(activity_date = structure(c(18273, 18274, 18274), class = "Date"),
  activity_time = c("05:26:01", "03:12:34", "23:26:47"), activity_position = c("POINT (0 0)", "POINT (2.6 3.8)", "POINT (3 0.6)"), activity_number = c(1L, 1L, 1L),
  grounding = c(FALSE, FALSE, TRUE), vesselactivity_code = c("2", "6", "13")), row.names = c(NA, -3L), class = c("tbl_df", "tbl", "data.frame")), data_activity = structure(
    list(vessel_code = "0", trip_enddate = structure(18281, class = "Date"), activity_date = structure(18273, class = "Date"), activity_time = "05:26:01",
    activity_position = "POINT (0 0)", activity_number = 1L, grounding = FALSE, vesselactivity_code = "2", X = "E0°0'", Y = "N0°0'"), class = "data.frame", row.names = 3L),
  data_vms = structure(list(vms_position = c("POINT (4 4)", "POINT (0 0.1)", "POINT (3 0.3)"), vms_date = structure(c(18273, 18274, 18274), class = "Date"), vms_time = c(
    "15:26:01", "10:55:15", "22:32:17"), distance = structure(c(339.502583, 6.004055, 181.019203), units = structure(list(numerator = "NM", denominator = character(0)),
  class = "symbolic_units"), class = "units"), duration = structure(c(NA_real_, NA_real_, NA_real_), units = structure(list(numerator = "ms", denominator = character(0)),
  class = "symbolic_units"), class = "units"), score = c(NA_real_, NA_real_, NA_real_)), class = "data.frame", row.names = 7:9), crs_activity = 4326, crs_vms = 4326),
  `4` = list(data_trip = structure(list(activity_date = structure(c(18274, 18274, 18273), class = "Date"), activity_time = c("03:12:34", "23:26:47", "05:26:01"),
  activity_position = c("POINT (2.6 3.8)", "POINT (3 0.6)", "POINT (0 0)"), activity_number = c(1L, 1L, 1L), grounding = c(FALSE, TRUE, FALSE), vesselactivity_code = c(
    "6", "13", "2")), row.names = c(NA, -3L), class = c("tbl_df", "tbl", "data.frame")), data_activity = structure(list(vessel_code = "0", trip_enddate = structure(18281,
    class = "Date"), activity_date = structure(18274, class = "Date"), activity_time = "03:12:34", activity_position = "POINT (2.6 3.8)", activity_number = 1L,
  grounding = FALSE, vesselactivity_code = "6", X = "E2°36'", Y = "N3°48'"), class = "data.frame", row.names = 1L), data_vms = structure(list(vms_position = c(
    "POINT (0 0.1)", "POINT (3 0.3)", "POINT (4 4)"), vms_date = structure(c(18274, 18274, 18273), class = "Date"), vms_time = c("10:55:15", "22:32:17", "15:26:01"),
  distance = structure(c(271.445826973379, 211.507663354955, 84.71741855987), units = structure(list(numerator = "NM", denominator = character(0)), class = "symbolic_units"),
  class = "units"), duration = structure(c(-27761000, -69583000, -44007000), units = structure(list(numerator = "ms", denominator = character(0)), class = "symbolic_units"),
  class = "units"), score = c(0, 0, 0)), class = "data.frame", row.names = c(NA, 3L)), crs_activity = 4326, crs_vms = 4326), `6` = list(data_trip = structure(list(
    activity_date = structure(c(18274, 18274, 18273), class = "Date"), activity_time = c("03:12:34", "23:26:47", "05:26:01"), activity_position = c("POINT (2.6 3.8)",
      "POINT (3 0.6)", "POINT (0 0)"), activity_number = c(1L, 1L, 1L), grounding = c(FALSE, TRUE, FALSE), vesselactivity_code = c("6", "13", "2")), row.names = c(NA,
    -3L), class = c("tbl_df", "tbl", "data.frame")), data_activity = structure(list(vessel_code = "0", trip_enddate = structure(18281, class = "Date"), activity_date = structure(
    18274, class = "Date"), activity_time = "23:26:47", activity_position = "POINT (3 0.6)", activity_number = 1L, grounding = TRUE, vesselactivity_code = "13", X = "E3°0'",
  Y = "N0°36'"), class = "data.frame", row.names = 2L), data_vms = structure(list(vms_position = c("POINT (0 0.1)", "POINT (3 0.3)", "POINT (4 4)"), vms_date = structure(
    c(18274, 18274, 18273), class = "Date"), vms_time = c("10:55:15", "22:32:17", "15:26:01"), distance = structure(c(182.602328607533, 18.012165417519, 212.768118823317),
  units = structure(list(numerator = "NM", denominator = character(0)), class = "symbolic_units"), class = "units"), duration = structure(c(45092000, 3270000, 28846000),
  units = structure(list(numerator = "ms", denominator = character(0)), class = "symbolic_units"), class = "units"), score = c(0, 0.209441144555651, 0)), class = "data.frame",
  row.names = 4:6), crs_activity = 4326, crs_vms = 4326)))
})

