# Generated by doctest: do not edit by hand
# Please edit file in R/function.R

test_that("Doctest: check_distribution_inspector", {
  # Created from @doctest for `check_distribution_inspector`
  # Source file: R/function.R
  # Source line: 5550
  dataframe1 <- data.frame(sample_id = c("1", "2", "3", "4", "5", "6"), sample_well = c("well_1", "well_2", "well_3", "well_4", "well_5", "well_6"), trip_id = c(
    "1", "1", "1", "1", "1", "1"), sample_smallsweight = c(6, 25, 14, 0, NA, 10), sample_bigsweight = c(12, 0, 9, NA, 6, 0))
  dataframe2 <- data.frame(well_id = c("1", "2", "3", "4", "5", "6"), well_label = c("well_1", "well_2", "well_3", "well_4", "well_5", "well_6"), trip_id = c(
    "1", "1", "1", "1", "1", "1"))
  dataframe3 <- data.frame(wellactivity_id = c("1", "2", "3", "4", "5", "6", "7"), well_id = c("1", "1", "2", "3", "4", "5", "6"))
  dataframe4 <- data.frame(wellactivityspecies_id = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"), wellactivity_id = c("1", "1", "1", "2",
    "3", "4", "4", "5", "6", "7", "7", "7"), weightcategory_code = c("W-1", "W-9", "W-2", "W-2", "W-1", "W-2", "W-9", "W-2", "W-2", "W-1", "W-9", "W-9"),
  species_fao_code = c("BET", "SKJ", "SKJ", "ALB", "SKJ", "BET", "BET", "ALB", "SKJ", "SKJ", "SKJ", "BET"), wellactivityspecies_weight = c(4, 2, 7, 5, 25, 9, 14,
    5, 17, 10, 5, 2))
  expect_equal(check_distribution_inspector(dataframe1, dataframe2, dataframe3, dataframe4, output = "report"), structure(list(sample_id = c("1", "2", "3", "4",
    "5", "6"), logical = c(TRUE, TRUE, FALSE, FALSE, FALSE, FALSE), sample_smallsweight = c(6, 25, 14, 0, NA, 10), sample_bigsweight = c(12, 0, 9, NA, 6, 0),
  sample_well = c("well_1", "well_2", "well_3", "well_4", "well_5", "well_6"), weight_small_total = c(6, 25, NaN, NaN, NaN, 15), weight_big = c(12, NA, 9, 5, 17,
    NA)), row.names = c(NA, -6L), class = c("tbl_df", "tbl", "data.frame")))
})

