# Generated by doctest: do not edit by hand
# Please edit file in R/function_specific_check.R

test_that("Doctest: display_raising_factor", {
  # Created from @doctest for `display_raising_factor`
  # Source file: R/function_specific_check.R
  # Source line: 13
  dataframe1 <- data.frame(rf1 = c(1, 1.11111111111111, 2.55555))
  expect_equal(display_raising_factor(dataframe1), structure(list(rf1 = c(1, 1.11111, 2.55555)), row.names = c(NA, -3L), class = "data.frame"))
})

