# Generated by doctest: do not edit by hand
# Please edit file in R/function_toolbox.R

test_that("Doctest: text_object_more_or_less", {
  # Created from @doctest for `text_object_more_or_less`
  # Source file: R/function_toolbox.R
  # Source line: 262
  expect_equal(text_object_more_or_less(id = c("1", "2", "3"), result_check = c("1", "3", "3")), "Missing item (1):2\nToo many item (1):3")
})

