# Generated by doctest: do not edit by hand
# Please edit file in R/function_specific_check.R

test_that("Doctest: plot_anapo_activity_data", {
  # Created from @doctest for `plot_anapo_activity_data`
  # Source file: R/function_specific_check.R
  # Source line: 1675
  dataframe1 <- data.frame(vms_id = c("1", "2"), vessel_code = c("0", "0"), vms_date = as.Date(c("2020/01/13", "2020/01/13")), vessel_type = c("6", "6"))
  dataframe2 <- data.frame(vms_id = c("1", "2"), vms_time = c("10:55:15", "22:32:17"), vms_position = c("POINT (0 0.1)", "POINT (3 0.3)"), vms_crs = c(4326,
    4326))
  expect_equal(plot_anapo_activity_data(dataframe1, dataframe2), list(`1` = list(data_vms = structure(list(vms_position = "POINT (0 0.1)", vms_time = "10:55:15"),
  class = "data.frame", row.names = 1L), date_vms = structure(18274, class = "Date"), crs_vms = 4326, vessel_code = "0", vessel_type = "6"), `2` = list(
    data_vms = structure(list(vms_position = "POINT (3 0.3)", vms_time = "22:32:17"), class = "data.frame", row.names = 2L), date_vms = structure(18274,
      class = "Date"), crs_vms = 4326, vessel_code = "0", vessel_type = "6")))
})

