# Generated by doctest: do not edit by hand
# Please edit file in R/function_toolbox.R

test_that("Doctest: coordinate_dd_to_dmd", {
  # Created from @doctest for `coordinate_dd_to_dmd`
  # Source file: R/function_toolbox.R
  # Source line: 310
  expect_equal(coordinate_dd_to_dmd(coordinate = c(0.1, 5.69), latitude = TRUE), c("N0°6'", "N5°41.4'"))
})

